// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YeniEmlak.Models;

namespace YeniEmlak.Migrations
{
    [DbContext(typeof(YeniEmlakDbContext))]
    [Migration("20190226135404_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YeniEmlak.Models.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdvertisementType");

                    b.Property<int?>("EstateId");

                    b.HasKey("Id");

                    b.HasIndex("EstateId");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("YeniEmlak.Models.Estate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<long>("Area");

                    b.Property<int>("City");

                    b.Property<int>("EstateType");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Estates");
                });

            modelBuilder.Entity("YeniEmlak.Models.Advertisement", b =>
                {
                    b.HasOne("YeniEmlak.Models.Estate", "Estate")
                        .WithMany()
                        .HasForeignKey("EstateId");
                });
#pragma warning restore 612, 618
        }
    }
}
